# Generated by Django 5.0.4 on 2024-04-08 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('isbn', models.CharField(max_length=10)),
                ('genre', models.CharField(choices=[('POLITICS', 'Politics'), ('FINANCE', 'Finance'), ('ROMANCE', 'Romance')], default='P', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.authors')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('due_back', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable')], default='A', max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.book')),
            ],
        ),
    ]
