# Generated by Django 5.0.4 on 2024-04-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_genre_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='authors',
            name='last_name',
            field=models.CharField(default='samuel', max_length=255),
            preserve_default=False,
        ),
    ]
