# Generated by Django 5.0.4 on 2024-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
