# Generated by Django 5.0.4 on 2024-04-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_review_book_alter_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/images')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_image', to='catalog.book')),
            ],
        ),
    ]
